const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const tags = [
  ["operations", "Operations", "Workflow and operational coordination problems."],
  ["field-service", "Field Service", "Dispatch, scheduling, and mobile team tooling."],
  ["agency", "Agency", "Client service and project delivery workflows."],
  ["commerce", "Commerce", "Retail and merchant operations software."],
  ["logistics", "Logistics", "Movement of goods, exceptions, and scheduling."],
  ["compliance", "Compliance", "Documentation, approvals, and audit readiness."],
  ["healthcare", "Healthcare", "Operational tooling for clinics and care teams."],
  ["education", "Education", "Software problems for schools and training providers."],
  ["hospitality", "Hospitality", "Hotel and guest experience operations."],
  ["finance", "Finance", "Cash flow, approvals, and reporting."],
];

const stacks = [
  ["next-js", "Next.js", "Frontend", "React framework for modern web apps."],
  ["react-native", "React Native", "Mobile", "Cross-platform mobile app development."],
  ["postgresql", "PostgreSQL", "Database", "Reliable relational storage for product data."],
  ["supabase", "Supabase", "Platform", "Managed Postgres, auth, and storage."],
  ["stripe", "Stripe", "Payments", "Subscription and payments infrastructure."],
  ["resend", "Resend", "Messaging", "Transactional email and notification delivery."],
  ["openai-api", "OpenAI API", "AI", "Summaries, copilots, and evidence extraction."],
  ["mapbox", "Mapbox", "Mapping", "Maps and route visualization."],
];

const problems = [
  {
    slug: "dispatch-planning-for-independent-electricians",
    title: "Dispatch planning for independent electricians",
    tagline: "Coordinate jobs, travel windows, and technician availability without whiteboards.",
    excerpt: "Small electrical teams still rely on calls, notes, and spreadsheets to schedule daily jobs.",
    summary: "Independent electrical contractors need a lightweight dispatch tool that handles urgent calls, route grouping, and technician load balancing.",
    description: "Owners of small electrical businesses often schedule work from their phone while technicians are already on the road. Existing field-service suites are too expensive and bloated, while generic calendars do not capture quote status, travel time, or job urgency.",
    targetUser: "Owners and dispatchers at 3-15 person electrical service companies",
    painPoint: "The team loses time to manual scheduling, double-booking, unclear technician assignments, and missed customer updates.",
    suggestedMvp: "A dispatcher dashboard with technician views, drag-and-drop day planning, SMS ETA updates, and job status tracking.",
    demandSignalsSummary: "Trade forums and job posts repeatedly mention dispatch overload once a company grows beyond a few vans.",
    riskNotes: "The market has incumbents, so the wedge needs to be speed, simplicity, and a small-team price point.",
    category: "Operations",
    industry: "Field Services",
    geographyFocus: "US and Canada",
    companySize: "3-15 employees",
    recommendedSkill: "INTERMEDIATE",
    projectTypes: ["SAAS", "SERVICE_BUSINESS_TOOL"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "PUBLISHED",
    buildTimeValue: 6,
    buildTimeUnit: "WEEKS",
    difficultyScore: 61,
    demandScore: 84,
    monetizationScore: 76,
    validationScore: 78,
    editorialScore: 81,
    featured: true,
    publishedAt: new Date("2026-02-10T08:30:00.000Z"),
    tagSlugs: ["operations", "field-service"],
    stackSlugs: ["next-js", "postgresql", "mapbox", "resend"],
    evidences: [
      {
        title: "Trade forum complaints about dispatcher overload",
        summary: "Owners describe losing hours every morning rearranging jobs and routes.",
        sourceType: "FORUM",
        sourceName: "ElectricianTalk",
        sourceUrl: "https://www.electriciantalk.com/",
        snippet: "Several shop owners mention whiteboards and spreadsheets breaking down once crews exceed five vans.",
        signalStrength: 4,
        capturedAt: new Date("2026-01-18T10:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Niche angle",
        body: "Position against bloated field-service suites and lead with same-day scheduling.",
        createdBy: "editor@problematlas.dev",
        pinned: true,
      },
    ],
  },
  {
    slug: "client-onboarding-for-boutique-agencies",
    title: "Client onboarding for boutique agencies",
    tagline: "Replace scattered kickoff emails with a single intake and approval workflow.",
    excerpt: "Small agencies burn hours chasing assets, approvals, and project basics during onboarding.",
    summary: "Boutique agencies need a structured intake and client portal to capture materials, timelines, and stakeholder approvals before delivery work starts.",
    description: "Creative and digital agencies often start projects with email threads, shared folders, and ad hoc forms. Important brand assets go missing, access requests get delayed, and clients are unsure what to send.",
    targetUser: "Agency founders and operations managers at 2-25 person agencies",
    painPoint: "New engagements start slowly because clients do not know what to provide and the internal team lacks a consistent checklist.",
    suggestedMvp: "Reusable onboarding templates, asset collection, stakeholder approvals, and timeline checkpoints.",
    demandSignalsSummary: "Agency operators consistently discuss broken kickoff workflows, delayed access requests, and messy client communication.",
    riskNotes: "Agencies already use project tools, so this product needs to own the pre-delivery onboarding niche clearly.",
    category: "Agency",
    industry: "Professional Services",
    geographyFocus: "Global",
    companySize: "2-25 employees",
    recommendedSkill: "BEGINNER",
    projectTypes: ["SAAS", "INTERNAL_TOOL"],
    monetizationTypes: ["SUBSCRIPTION", "AGENCY_UPSELL"],
    status: "PUBLISHED",
    buildTimeValue: 4,
    buildTimeUnit: "WEEKS",
    difficultyScore: 43,
    demandScore: 79,
    monetizationScore: 69,
    validationScore: 74,
    editorialScore: 77,
    featured: true,
    publishedAt: new Date("2026-02-12T09:00:00.000Z"),
    tagSlugs: ["agency", "operations"],
    stackSlugs: ["next-js", "postgresql", "resend", "stripe"],
    evidences: [
      {
        title: "Agency ops communities share onboarding checklists",
        summary: "Founders compare manual kickoff documents and recurring asset gaps.",
        sourceType: "FORUM",
        sourceName: "r/agency",
        sourceUrl: "https://www.reddit.com/r/agency/",
        snippet: "Threads repeatedly ask for a better way to collect logos, copy, access, and approvals from clients.",
        signalStrength: 4,
        capturedAt: new Date("2026-01-09T11:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Go-to-market",
        body: "Templates and white-labeled client portals could be the best acquisition wedge.",
        createdBy: "editor@problematlas.dev",
        pinned: false,
      },
    ],
  },
  {
    slug: "inventory-forecasting-for-neighborhood-retailers",
    title: "Inventory forecasting for neighborhood retailers",
    tagline: "Give small merchants better reorder timing without enterprise software.",
    excerpt: "Independent stores struggle to predict stockouts and over-ordering with simple POS exports.",
    summary: "Retailers with one to five storefronts need a lightweight forecasting layer that turns sales history into practical reorder recommendations.",
    description: "Smaller retailers often have transaction data but no affordable way to model replenishment timing, slow-moving products, or seasonal shifts. Existing forecasting tools are usually built for chains with dedicated analysts.",
    targetUser: "Owners and operations leads at neighborhood retail chains",
    painPoint: "Cash gets tied up in slow inventory while fast-moving items stock out due to reactive reordering.",
    suggestedMvp: "CSV import from common POS tools, reorder suggestions, slow-stock alerts, and weekly purchase lists.",
    demandSignalsSummary: "Retail operators repeatedly ask for practical forecasting help that fits smaller catalogs and tighter budgets.",
    riskNotes: "Data cleanliness can be poor, so the product must be resilient to messy exports and partial records.",
    category: "Commerce",
    industry: "Retail",
    geographyFocus: "US, UK, and Australia",
    companySize: "1-5 locations",
    recommendedSkill: "INTERMEDIATE",
    projectTypes: ["ANALYTICS", "SAAS"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "PUBLISHED",
    buildTimeValue: 8,
    buildTimeUnit: "WEEKS",
    difficultyScore: 58,
    demandScore: 82,
    monetizationScore: 73,
    validationScore: 71,
    editorialScore: 79,
    featured: true,
    publishedAt: new Date("2026-02-15T08:15:00.000Z"),
    tagSlugs: ["commerce", "finance"],
    stackSlugs: ["next-js", "postgresql", "supabase"],
    evidences: [
      {
        title: "Search demand around stock forecasting templates",
        summary: "Merchants appear to be solving forecasting with spreadsheets and ad hoc templates.",
        sourceType: "SEARCH_TREND",
        sourceName: "Google Trends",
        sourceUrl: "https://trends.google.com/",
        snippet: "Searches for reorder templates and inventory forecasting remain consistently active.",
        signalStrength: 3,
        capturedAt: new Date("2026-01-21T12:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Data challenge",
        body: "A strong import story for Square, Shopify POS, and Lightspeed matters here.",
        createdBy: "editor@problematlas.dev",
        pinned: true,
      },
    ],
  },
  {
    slug: "maintenance-scheduling-for-small-property-managers",
    title: "Maintenance scheduling for small property managers",
    tagline: "Coordinate repairs, vendors, and tenant updates from one calmer workflow.",
    excerpt: "Small property managers are buried in repair requests, vendor coordination, and status follow-up.",
    summary: "Property managers need a repair workflow tool that organizes incoming issues, vendor assignment, and resident communication.",
    description: "Smaller property operators often stitch together email, phone calls, and shared spreadsheets to manage maintenance. Tenants want faster updates and owners want documentation, but existing property suites can be clunky or overkill.",
    targetUser: "Independent property managers and small management firms",
    painPoint: "Repair requests disappear into inboxes, vendors are hard to coordinate, and tenants repeatedly ask for updates.",
    suggestedMvp: "Resident request intake, vendor assignment board, appointment windows, and status notifications.",
    demandSignalsSummary: "Property managers consistently describe maintenance coordination as the most chaotic operational area.",
    riskNotes: "Integration pressure from incumbent systems is real, so stand-alone workflows may be the cleanest first version.",
    category: "Operations",
    industry: "Real Estate",
    geographyFocus: "North America",
    companySize: "50-500 units managed",
    recommendedSkill: "INTERMEDIATE",
    projectTypes: ["SAAS", "SERVICE_BUSINESS_TOOL"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "PUBLISHED",
    buildTimeValue: 6,
    buildTimeUnit: "WEEKS",
    difficultyScore: 55,
    demandScore: 77,
    monetizationScore: 71,
    validationScore: 72,
    editorialScore: 75,
    featured: false,
    publishedAt: new Date("2026-02-18T10:00:00.000Z"),
    tagSlugs: ["operations", "compliance"],
    stackSlugs: ["next-js", "postgresql", "resend"],
    evidences: [
      {
        title: "Maintenance coordinator job descriptions highlight fragmented systems",
        summary: "Roles repeatedly mention juggling resident calls, vendors, and spreadsheets.",
        sourceType: "JOB_POSTING",
        sourceName: "LinkedIn Jobs",
        sourceUrl: "https://www.linkedin.com/jobs/",
        snippet: "Manual follow-up and documentation are recurring expectations in coordinator roles.",
        signalStrength: 3,
        capturedAt: new Date("2026-01-16T07:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Expansion path",
        body: "Inspections and preventive maintenance could become a second module later.",
        createdBy: "editor@problematlas.dev",
        pinned: false,
      },
    ],
  },
  {
    slug: "compliance-reminder-hub-for-food-manufacturers",
    title: "Compliance reminder hub for food manufacturers",
    tagline: "Track recurring certifications, audits, and document deadlines in one place.",
    excerpt: "Smaller food producers juggle audits, certifications, and expiring documents across scattered spreadsheets.",
    summary: "Food manufacturing teams need a compliance operations dashboard that monitors deadlines and assigns follow-up work.",
    description: "Growing food businesses face recurring audits, supplier document expiration, and policy review cycles. These tasks often live in personal reminders or fragmented spreadsheets, which raises operational risk.",
    targetUser: "Operations and quality leads at small food manufacturers",
    painPoint: "Critical compliance dates and supplier paperwork are hard to track consistently as the business grows.",
    suggestedMvp: "Recurring deadline tracking, document owners, evidence attachments, and audit readiness checklists.",
    demandSignalsSummary: "Quality teams often discuss certification calendars and document control pain as under-served by modern tools.",
    riskNotes: "The product must avoid implying legal sufficiency and stay positioned as workflow support.",
    category: "Compliance",
    industry: "Food Manufacturing",
    geographyFocus: "US and EU",
    companySize: "20-200 employees",
    recommendedSkill: "ADVANCED",
    projectTypes: ["SAAS", "INTERNAL_TOOL"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "REVIEW",
    buildTimeValue: 10,
    buildTimeUnit: "WEEKS",
    difficultyScore: 67,
    demandScore: 74,
    monetizationScore: 72,
    validationScore: 63,
    editorialScore: 70,
    featured: false,
    publishedAt: null,
    tagSlugs: ["compliance", "operations"],
    stackSlugs: ["next-js", "postgresql", "supabase"],
    evidences: [
      {
        title: "Quality managers ask for better supplier document tracking",
        summary: "Discussions center on expiring certificates and fragmented audit prep.",
        sourceType: "FORUM",
        sourceName: "IFSQN",
        sourceUrl: "https://www.ifsqn.com/",
        snippet: "Teams compare spreadsheets and shared drives for supplier and audit records.",
        signalStrength: 4,
        capturedAt: new Date("2026-01-28T14:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Needs expert review",
        body: "Worth validating with a few QA leads before publishing.",
        createdBy: "editor@problematlas.dev",
        pinned: true,
      },
    ],
  },
  {
    slug: "patient-intake-ops-for-private-clinics",
    title: "Patient intake ops for private clinics",
    tagline: "Reduce front-desk friction with cleaner forms, reminders, and prep workflows.",
    excerpt: "Private clinics still chase patient forms, appointment prep, and missing intake data by phone.",
    summary: "Private clinics need a better pre-visit workflow that collects forms, confirms details, and flags missing information before appointments.",
    description: "Many private clinics rely on manual calls and static forms to gather insurance details, pre-visit documents, and consent information. This creates front-desk bottlenecks and repeated patient outreach.",
    targetUser: "Clinic administrators and front-desk managers at small private practices",
    painPoint: "Staff spend too much time chasing missing forms and correcting intake details under time pressure.",
    suggestedMvp: "Pre-visit checklist, secure patient form collection, reminder flows, and missing-info alerts.",
    demandSignalsSummary: "Clinic administrators frequently discuss intake inefficiency, especially in practices without robust patient portals.",
    riskNotes: "Healthcare compliance and integrations raise complexity quickly, so the scope should stay operational rather than clinical.",
    category: "Operations",
    industry: "Healthcare",
    geographyFocus: "US",
    companySize: "1-10 clinicians",
    recommendedSkill: "ADVANCED",
    projectTypes: ["SAAS"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "DRAFT",
    buildTimeValue: 12,
    buildTimeUnit: "WEEKS",
    difficultyScore: 72,
    demandScore: 75,
    monetizationScore: 74,
    validationScore: 58,
    editorialScore: 68,
    featured: false,
    publishedAt: null,
    tagSlugs: ["healthcare", "operations"],
    stackSlugs: ["next-js", "postgresql", "resend"],
    evidences: [
      {
        title: "Private practice admins describe front-desk overload",
        summary: "Front-office staff report repeated manual outreach for forms and reminders.",
        sourceType: "SOCIAL_POST",
        sourceName: "LinkedIn",
        sourceUrl: "https://www.linkedin.com/",
        snippet: "Posts from clinic operators emphasize no-shows, incomplete paperwork, and intake bottlenecks.",
        signalStrength: 3,
        capturedAt: new Date("2026-02-04T09:30:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Regulatory caution",
        body: "Keep positioning around intake operations rather than medical record management.",
        createdBy: "editor@problematlas.dev",
        pinned: true,
      },
    ],
  },
  {
    slug: "student-placement-tracker-for-bootcamps",
    title: "Student placement tracker for bootcamps",
    tagline: "Track outreach, interviews, and outcomes without juggling spreadsheets.",
    excerpt: "Career services teams at bootcamps often run placement support from manually updated spreadsheets.",
    summary: "Career support teams need a system for student job-seeking progress, employer outreach, and placement reporting.",
    description: "Bootcamps and cohort-based training programs need better visibility into employer outreach, student application activity, and placement status. General CRMs can work, but they are often hard to adapt to education workflows.",
    targetUser: "Career services managers at coding bootcamps and training academies",
    painPoint: "Placement reporting is tedious and student follow-up becomes inconsistent when managed across spreadsheets.",
    suggestedMvp: "Student pipeline tracking, employer contact records, follow-up reminders, and outcome reporting dashboards.",
    demandSignalsSummary: "Training programs repeatedly discuss outcomes reporting and employer follow-up as manually intensive work.",
    riskNotes: "The target market can be budget sensitive, so the product must show obvious time savings.",
    category: "Education",
    industry: "Education",
    geographyFocus: "Global",
    companySize: "50-1000 students per year",
    recommendedSkill: "INTERMEDIATE",
    projectTypes: ["SAAS", "ANALYTICS"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "PUBLISHED",
    buildTimeValue: 5,
    buildTimeUnit: "WEEKS",
    difficultyScore: 49,
    demandScore: 70,
    monetizationScore: 61,
    validationScore: 69,
    editorialScore: 71,
    featured: false,
    publishedAt: new Date("2026-02-21T08:00:00.000Z"),
    tagSlugs: ["education", "operations"],
    stackSlugs: ["next-js", "postgresql", "resend"],
    evidences: [
      {
        title: "Outcome reporting pain shows up in education ops communities",
        summary: "Teams discuss difficulty standardizing follow-up and tracking job-search progress.",
        sourceType: "FORUM",
        sourceName: "Training provider Slack communities",
        sourceUrl: null,
        snippet: "Staff often compare sheets and Airtable bases for employer outreach and placement records.",
        signalStrength: 3,
        capturedAt: new Date("2026-01-20T13:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Possible wedge",
        body: "Outcome transparency pressure could make dashboards especially compelling.",
        createdBy: "editor@problematlas.dev",
        pinned: false,
      },
    ],
  },
  {
    slug: "vendor-coordination-for-boutique-hotels",
    title: "Vendor coordination for boutique hotels",
    tagline: "Manage recurring property vendors, inspections, and follow-up without inbox chaos.",
    excerpt: "Boutique hotels coordinate cleaners, maintenance vendors, and seasonal prep through email and calls.",
    summary: "Independent hospitality operators need a central workflow for vendor schedules, property tasks, and service confirmations.",
    description: "Smaller hotels and lodging groups rely on multiple external vendors but often lack a simple system to schedule them, log completion, and maintain accountability. The result is missed tasks, repeated phone calls, and patchy service records.",
    targetUser: "Operations managers at boutique hotels and lodge groups",
    painPoint: "Property tasks are hard to coordinate consistently across recurring vendors and changing occupancy demands.",
    suggestedMvp: "Vendor calendar, recurring task scheduling, completion logs, and exception alerts for missed work.",
    demandSignalsSummary: "Hospitality operators frequently describe fragmented maintenance and vendor coordination as a hidden drag on service quality.",
    riskNotes: "Target independent groups with enough recurring vendor complexity to justify software spend.",
    category: "Hospitality",
    industry: "Hospitality",
    geographyFocus: "North America and Europe",
    companySize: "1-10 properties",
    recommendedSkill: "INTERMEDIATE",
    projectTypes: ["SAAS", "SERVICE_BUSINESS_TOOL"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "PUBLISHED",
    buildTimeValue: 7,
    buildTimeUnit: "WEEKS",
    difficultyScore: 56,
    demandScore: 68,
    monetizationScore: 67,
    validationScore: 65,
    editorialScore: 69,
    featured: false,
    publishedAt: new Date("2026-02-23T10:30:00.000Z"),
    tagSlugs: ["hospitality", "operations"],
    stackSlugs: ["next-js", "postgresql", "resend"],
    evidences: [
      {
        title: "Hotel operations groups discuss recurring vendor misses",
        summary: "Operators compare manual scheduling methods for cleaners, inspectors, and contractors.",
        sourceType: "SOCIAL_POST",
        sourceName: "Hospitality LinkedIn groups",
        sourceUrl: "https://www.linkedin.com/",
        snippet: "Missed follow-up and vendor visibility are recurring complaints among independent operators.",
        signalStrength: 3,
        capturedAt: new Date("2026-01-30T16:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Packaging idea",
        body: "Frame this as a calmer alternative to general project-management tools.",
        createdBy: "editor@problematlas.dev",
        pinned: false,
      },
    ],
  },
  {
    slug: "cash-flow-planner-for-specialty-contractors",
    title: "Cash flow planner for specialty contractors",
    tagline: "Help trade businesses predict cash gaps tied to deposits, milestones, and receivables.",
    excerpt: "Growing contractors struggle to plan cash timing across deposits, payroll, and delayed receivables.",
    summary: "Specialty contractors need a planning layer that forecasts cash pressure based on project schedules and expected payments.",
    description: "Small construction and trade firms often understand their revenue pipeline but still get caught by timing gaps between deposits, payroll cycles, materials, and final invoice collection. Accounting tools show the ledger but not the near-term operational picture.",
    targetUser: "Owners and finance leads at specialty contracting firms",
    painPoint: "Cash gaps create stress around payroll and materials because invoice timing is hard to visualize in advance.",
    suggestedMvp: "Project cash timeline, expected payment milestones, payroll overlays, and weekly gap alerts.",
    demandSignalsSummary: "Contractor communities frequently discuss cash timing and delayed receivables as existential growth pains.",
    riskNotes: "Financial workflows require trust, so keep the modeling simple and explainable.",
    category: "Finance",
    industry: "Construction",
    geographyFocus: "US",
    companySize: "5-50 employees",
    recommendedSkill: "INTERMEDIATE",
    projectTypes: ["ANALYTICS", "SAAS"],
    monetizationTypes: ["SUBSCRIPTION"],
    status: "PUBLISHED",
    buildTimeValue: 8,
    buildTimeUnit: "WEEKS",
    difficultyScore: 60,
    demandScore: 80,
    monetizationScore: 75,
    validationScore: 73,
    editorialScore: 80,
    featured: true,
    publishedAt: new Date("2026-02-25T07:45:00.000Z"),
    tagSlugs: ["finance", "field-service"],
    stackSlugs: ["next-js", "postgresql", "stripe"],
    evidences: [
      {
        title: "Contractor forums highlight invoice timing pain",
        summary: "Owners discuss payroll stress despite healthy booked work.",
        sourceType: "FORUM",
        sourceName: "Contractor Talk",
        sourceUrl: "https://www.contractortalk.com/",
        snippet: "Delayed draws and final payments are a recurring source of cash anxiety.",
        signalStrength: 4,
        capturedAt: new Date("2026-01-11T15:00:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Messaging",
        body: "Emphasize visibility and planning, not bookkeeping replacement.",
        createdBy: "editor@problematlas.dev",
        pinned: true,
      },
    ],
  },
  {
    slug: "procurement-approval-tracker-for-nonprofits",
    title: "Procurement approval tracker for nonprofits",
    tagline: "Keep purchase requests, approvals, and audit trails out of chaotic email chains.",
    excerpt: "Nonprofits often handle purchasing approvals manually, creating delays and audit headaches.",
    summary: "Operations teams at nonprofits need a clearer workflow for purchase requests, approvals, and supporting documentation.",
    description: "Mission-driven organizations usually have lean operations teams and layered approval requirements for spending. Requests arrive by email or chat, documentation gets lost, and finance teams struggle to reconstruct an audit trail later.",
    targetUser: "Operations and finance managers at nonprofits and NGOs",
    painPoint: "Purchasing slows down because requests lack a clear path, and teams scramble for documentation during audits.",
    suggestedMvp: "Purchase request forms, configurable approvals, receipts and quote uploads, and exportable audit history.",
    demandSignalsSummary: "Nonprofit ops leaders regularly mention manual approvals and spending documentation as recurring pain.",
    riskNotes: "Budgets can be tight, so simple pricing and donor-compliance messaging will matter.",
    category: "Compliance",
    industry: "Nonprofit",
    geographyFocus: "Global",
    companySize: "10-200 employees",
    recommendedSkill: "BEGINNER",
    projectTypes: ["INTERNAL_TOOL", "SAAS"],
    monetizationTypes: ["SUBSCRIPTION", "ONE_TIME_LICENSE"],
    status: "REVIEW",
    buildTimeValue: 5,
    buildTimeUnit: "WEEKS",
    difficultyScore: 45,
    demandScore: 66,
    monetizationScore: 58,
    validationScore: 62,
    editorialScore: 64,
    featured: false,
    publishedAt: null,
    tagSlugs: ["compliance", "finance"],
    stackSlugs: ["next-js", "postgresql", "supabase"],
    evidences: [
      {
        title: "Ops leaders compare manual approval processes",
        summary: "Teams describe reconciling requests from inboxes, forms, and chat threads.",
        sourceType: "SOCIAL_POST",
        sourceName: "Operations communities",
        sourceUrl: null,
        snippet: "Audit preparation gets painful because decisions and receipts live in too many places.",
        signalStrength: 3,
        capturedAt: new Date("2026-02-02T10:45:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Potential distribution",
        body: "Partnerships with nonprofit consultants could help reach the right operators.",
        createdBy: "editor@problematlas.dev",
        pinned: false,
      },
    ],
  },
  {
    slug: "shipment-exception-dashboard-for-importers",
    title: "Shipment exception dashboard for importers",
    tagline: "Track delays, document gaps, and customs exceptions before they become fire drills.",
    excerpt: "Import teams stitch together freight updates, documents, and exception handling across email and portals.",
    summary: "Small importers need a control tower for delayed shipments, missing documents, and customs-related exceptions.",
    description: "Import operations teams often monitor shipments across freight forwarder emails, shared spreadsheets, and carrier portals. The painful moments are not standard updates but exceptions: missing paperwork, customs holds, and date changes that affect downstream stock.",
    targetUser: "Operations managers at import-heavy distributors and brands",
    painPoint: "Teams react too slowly to shipment exceptions because information is fragmented across providers and channels.",
    suggestedMvp: "Shipment list, exception tagging, owner assignment, due dates, and timeline-based resolution notes.",
    demandSignalsSummary: "Importers repeatedly mention email overload and exception visibility as a major operational drag.",
    riskNotes: "Integrations can get deep quickly, so the first version should accept manual updates and email forwarding.",
    category: "Logistics",
    industry: "Import / Distribution",
    geographyFocus: "US and EU",
    companySize: "5-100 employees",
    recommendedSkill: "ADVANCED",
    projectTypes: ["SAAS", "ANALYTICS"],
    monetizationTypes: ["SUBSCRIPTION", "USAGE_BASED"],
    status: "PUBLISHED",
    buildTimeValue: 10,
    buildTimeUnit: "WEEKS",
    difficultyScore: 69,
    demandScore: 78,
    monetizationScore: 77,
    validationScore: 70,
    editorialScore: 78,
    featured: true,
    publishedAt: new Date("2026-02-28T09:45:00.000Z"),
    tagSlugs: ["logistics", "operations"],
    stackSlugs: ["next-js", "postgresql", "resend", "openai-api"],
    evidences: [
      {
        title: "Operations job posts emphasize exception management",
        summary: "Roles repeatedly mention customs holds, paperwork issues, and follow-up pressure.",
        sourceType: "JOB_POSTING",
        sourceName: "Indeed",
        sourceUrl: "https://www.indeed.com/",
        snippet: "Import coordinators are hired largely to stay on top of exceptions rather than routine updates.",
        signalStrength: 4,
        capturedAt: new Date("2026-01-27T08:20:00.000Z"),
      },
      {
        title: "Import operations communities discuss fragmented visibility",
        summary: "Teams use spreadsheets to reconcile updates from multiple partners.",
        sourceType: "FORUM",
        sourceName: "Freight forwarding communities",
        sourceUrl: null,
        snippet: "Exceptions remain the biggest source of operational surprises and customer frustration.",
        signalStrength: 3,
        capturedAt: new Date("2026-02-01T12:20:00.000Z"),
      },
    ],
    adminNotes: [
      {
        title: "Strong candidate",
        body: "Operational pain appears sharp and monetizable. Worth prioritizing for richer evidence collection.",
        createdBy: "editor@problematlas.dev",
        pinned: true,
      },
    ],
  },
];

const newsletterSignups = [
  {
    email: "maya@northstudioco.com",
    firstName: "Maya",
    source: "homepage",
    interests: ["Agency", "Operations"],
    confirmedAt: new Date("2026-02-11T08:00:00.000Z"),
    unsubscribedAt: null,
  },
  {
    email: "david@gridlineelectric.com",
    firstName: "David",
    source: "homepage",
    interests: ["Field Service", "Finance"],
    confirmedAt: new Date("2026-02-26T06:30:00.000Z"),
    unsubscribedAt: null,
  },
  {
    email: "lina@harborimports.co",
    firstName: "Lina",
    source: "problems",
    interests: ["Logistics", "Operations"],
    confirmedAt: new Date("2026-03-01T09:10:00.000Z"),
    unsubscribedAt: null,
  },
  {
    email: "sam@orchardclinic.org",
    firstName: "Sam",
    source: "homepage",
    interests: ["Healthcare", "Compliance"],
    confirmedAt: null,
    unsubscribedAt: null,
  },
];

async function main() {
  await prisma.adminNote.deleteMany();
  await prisma.problemEvidence.deleteMany();
  await prisma.newsletterSignup.deleteMany();
  await prisma.problem.deleteMany();
  await prisma.problemTag.deleteMany();
  await prisma.problemStack.deleteMany();

  await prisma.problemTag.createMany({
    data: tags.map(([slug, name, description]) => ({ slug, name, description })),
  });

  await prisma.problemStack.createMany({
    data: stacks.map(([slug, name, category, description]) => ({
      slug,
      name,
      category,
      description,
    })),
  });

  for (const problem of problems) {
    const { tagSlugs, stackSlugs, evidences, adminNotes, ...problemData } = problem;

    await prisma.problem.create({
      data: {
        ...problemData,
        tags: {
          connect: tagSlugs.map((slug) => ({ slug })),
        },
        stacks: {
          connect: stackSlugs.map((slug) => ({ slug })),
        },
        evidences: {
          create: evidences,
        },
        adminNotes: {
          create: adminNotes,
        },
      },
    });
  }

  await prisma.newsletterSignup.createMany({
    data: newsletterSignups,
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
